import { defineConfig } from 'vitest/config';

export default defineConfig({
  test: {
    globals: true,
    environment: 'node',
    testTimeout: 30000, // 30 seconds for API calls
    reporters: process.env.GITHUB_ACTIONS ? ['dot', 'github-actions'] : ['dot'],
    silent: 'passed-only',
    exclude: [
      // Removed providers - these tests reference providers that are no longer bundled
      'test/anthropic-cache-write-1h-cost.test.ts',
      'test/anthropic-empty-thinking-signature-compat.test.ts',
      'test/anthropic-force-adaptive-thinking.test.ts',
      'test/anthropic-opus-4-8-smoke.test.ts',
      'test/anthropic-sse-parsing.test.ts',
      'test/anthropic-temperature-compat.test.ts',
      'test/anthropic-thinking-disable.test.ts',
      'test/anthropic-tool-name-normalization.test.ts',
      'test/azure-openai-base-url.test.ts',
      'test/bedrock-convert-messages.test.ts',
      'test/bedrock-custom-headers.test.ts',
      'test/bedrock-endpoint-resolution.test.ts',
      'test/bedrock-thinking-payload.test.ts',
      'test/cache-retention.test.ts',
      'test/fireworks-models.test.ts',
      'test/github-copilot-anthropic.test.ts',
      'test/images-models.test.ts',
      'test/interleaved-thinking.test.ts',
      'test/lazy-module-load.test.ts',
      'test/max-thinking.test.ts',
      'test/models-runtime.test.ts',
      'test/openai-codex-cache-affinity-e2e.test.ts',
      'test/openai-completions-empty-tools.test.ts',
      'test/openai-completions-prompt-cache.test.ts',
      'test/openai-completions-tool-result-images.test.ts',
      'test/openai-responses-cache-affinity-e2e.test.ts',
      'test/openai-responses-empty-tool-result.test.ts',
      'test/openai-responses-foreign-toolcall-id.test.ts',
      'test/openai-responses-message-id.test.ts',
      'test/openai-responses-reasoning-replay-e2e.test.ts',
      'test/openai-responses-tool-result-images.test.ts',
      'test/provider-error-body-regression.test.ts',
      'test/together-models.test.ts',
      'test/xhigh.test.ts',
      'test/xiaomi-models.test.ts',
      // Mixed provider files that crash during discovery for removed providers
      'test/abort.test.ts',
      'test/deferred-tools.test.ts',
      'test/empty.test.ts',
      'test/image-tool-result.test.ts',
      'test/openai-completions-tool-choice.test.ts',
      'test/openai-responses-compat.test.ts',
      'test/responseid.test.ts',
      'test/stream.test.ts',
      'test/supports-xhigh.test.ts',
      'test/tokens.test.ts',
      'test/tool-call-without-result.test.ts',
      'test/unicode-surrogate.test.ts',
      // OAuth test uses device-code mock but openRouterOAuth uses PKCE callback
      'test/oauth-auth.test.ts',
    ],
  }
});