// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import { CLOUDFLARE_WORKERS_AI_MODELS } from "./providers/cloudflare-workers-ai.models.ts";
import { DEEPSEEK_MODELS } from "./providers/deepseek.models.ts";
import { GOOGLE_MODELS } from "./providers/google.models.ts";
import { GROQ_MODELS } from "./providers/groq.models.ts";
import { HUGGINGFACE_MODELS } from "./providers/huggingface.models.ts";
import { MISTRAL_MODELS } from "./providers/mistral.models.ts";
import { NVIDIA_MODELS } from "./providers/nvidia.models.ts";
import { OPENCODE_MODELS } from "./providers/opencode.models.ts";
import { OPENROUTER_MODELS } from "./providers/openrouter.models.ts";

export const MODELS: {
	readonly "cloudflare-workers-ai": typeof CLOUDFLARE_WORKERS_AI_MODELS;
	readonly "deepseek": typeof DEEPSEEK_MODELS;
	readonly "google": typeof GOOGLE_MODELS;
	readonly "groq": typeof GROQ_MODELS;
	readonly "huggingface": typeof HUGGINGFACE_MODELS;
	readonly "mistral": typeof MISTRAL_MODELS;
	readonly "nvidia": typeof NVIDIA_MODELS;
	readonly "opencode": typeof OPENCODE_MODELS;
	readonly "openrouter": typeof OPENROUTER_MODELS;
} = {
	"cloudflare-workers-ai": CLOUDFLARE_WORKERS_AI_MODELS,
	"deepseek": DEEPSEEK_MODELS,
	"google": GOOGLE_MODELS,
	"groq": GROQ_MODELS,
	"huggingface": HUGGINGFACE_MODELS,
	"mistral": MISTRAL_MODELS,
	"nvidia": NVIDIA_MODELS,
	"opencode": OPENCODE_MODELS,
	"openrouter": OPENROUTER_MODELS,
};
